#!/system/bin/sh

ID="$(id -u)"
NULL="/dev/null"
GMS="com.google.android.gms"
{ R="\e[1;31m" G="\e[1;32m" Y="\e[1;33m" N="\e[0m"; } 2> $NULL

CHK_OPT() {
    local OPT
    OPT="$(dumpsys deviceidle whitelist 2>/dev/null | grep "$GMS" | head -1)"
    if [ -z "$OPT" ]; then
        echo -e "$G $1 Optimized. $N"
    else
        echo -e "$R $1 Not Optimized. $N"
    fi
}

case $ID in
    0)
        CHK_OPT "Google Play Services is"
        ;;
    *)
        echo -e "$Y Superuser (su) rights required! $N"
        exit 1
        ;;
esac
